Lab03 Nathan Lokier
pcamarillor/O2024_ESI3914O pull request #106
Opened 2024-09-10 04:14 UTC by NathanLok7

2024-09-10 21:26 UTC, pcamarillor requested changes

2024-09-10 21:26 UTC, pcamarillor commented on src/lab03/solution_lab03_nathan_lokier.py
> +    return flights_df.groupBy("origin_country").agg(count("*").alias("total_flights")) \
Since you're inferring the schema (default option to `inferSchema`), the column with the origin country is `OriginCountry`, not `origin_country`. Check these inconsitencies: 

    pyspark.errors.exceptions.captured.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `origin_country` cannot be resolved. Did you mean one of the following? [`OriginCountry`, `Airline`, `DestinationCountry`, `FlightDate`, `FlightNumber`].;

2024-09-10 21:26 UTC, pcamarillor commented on src/lab03/solution_lab03_nathan_lokier.py
> +    avg_passengers = flights_df.groupBy("DestinationCountry").avg("Passengers")
The way you're creating the data frame is causing that `Passengers` columns is detected as string and not numeric:

     pyspark.errors.exceptions.captured.AnalysisException: "Passengers" is not a numeric column. Aggregation function can only be applied on a numeric column.

2024-09-10 21:26 UTC, pcamarillor commented on src/lab03/solution_lab03_nathan_lokier.py
> +    return flights_df.filter(flights_df["date"] == date)
There's no column named `date`:

    pyspark.errors.exceptions.captured.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `date` cannot be resolved. Did you mean one of the following? [`FlightNumber`, `Airline`, `OriginCountry`, `DestinationCountry`, `Passengers`, `FlightDate`].

2024-09-10 21:26 UTC, pcamarillor commented on src/lab03/solution_lab03_nathan_lokier.py
> +    return flights_df.filter((flights_df["origin_country"] == country_a) &
Not able to get column _origin_country_:

    pyspark.errors.exceptions.captured.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `origin_country` cannot be resolved. Did you mean one of the following? [`FlightNumber`, `Airline`, `OriginCountry`, `DestinationCountry`, `Passengers`, `FlightDate`].

2024-09-18 03:40 UTC, NathanLok7 commented
New code

2024-09-21 03:24 UTC, pcamarillor approved these changes

2024-09-21 03:25 UTC, merged