Add Team 5 Lab 12 notebook
pcamarillor/O2024_ESI3914O pull request #200
Opened 2024-11-08 03:21 UTC by lmfontes19

2024-11-11 03:01 UTC, pcamarillor commented on examples/notebooks/als/team5_lab12_ALS.ipynb
> +        "rmse = evaluator.evaluate(predictions)"
You computed correctly the RMSE, but you never show the value. Please add a print statement to show the RMSE

2024-11-11 03:02 UTC, pcamarillor requested changes
Just add a print statement to show the RMSE

2024-11-23 22:27 UTC, lmfontes19 commented on examples/notebooks/als/team5_lab12_ALS.ipynb
> +        "rmse = evaluator.evaluate(predictions)"
Thanks

2024-11-27 01:56 UTC, pcamarillor approved these changes

2024-11-27 01:56 UTC, merged