Gabriel olvera lab02
pcamarillor/O2024_ESI3914O pull request #79
Opened 2024-09-01 16:37 UTC by Gabored

Solution for Lab 02 using Functions with RDDs viewed in class

2024-09-01 20:49 UTC, pcamarillor requested changes
Test failed becase a blank space is detected as an IP:

      Common items:
      {'178.253.33.51': 6,
       '2.177.12.140': 12,
       '207.46.13.136': 3,
       '31.56.96.51': 4,
       '34.247.132.53': 1,
       '40.77.167.129': 10,
       '5.78.198.52': 3,
       '54.36.149.41': 1,
       '54.36.149.70': 1,
       '66.249.66.194': 5,
       '66.249.66.91': 2,
       '91.99.72.15': 4}
      Left contains 1 more item:
      {'': 1}
    
      Full diff:
        {
      +     '': 1,
            '178.253.33.51': 6,
            '2.177.12.140': 12,
            '207.46.13.136': 3,
            '31.56.96.51': 4,
            '34.247.132.53': 1,
            '40.77.167.129': 10,
            '5.78.198.52': 3,
            '54.36.149.41': 1,
            '54.36.149.70': 1,
            '66.249.66.194': 5,
            '66.249.66.91': 2,
            '91.99.72.15': 4,
        }
    =============================================================== 1 failed in 6.99s ===============================================================

2024-09-01 20:49 UTC, pcamarillor commented on src/lab02/solution_lab02_gabriel_olvera.py
> +    ip_rdd = log_rdd.map(lambda line: line.split(' ')[0])
This transformation looks good, but there's a blank line in the dataset and you're not considering such scenario in this solution.

2024-09-03 23:22 UTC, Gabored commented on src/lab02/solution_lab02_gabriel_olvera.py
> +    ip_rdd = log_rdd.map(lambda line: line.split(' ')[0])
Thanks teacher , I will resolve this by implementing a strcit filter strip for empty lines.  I will modify this files to approve this when this passes the correct test 

`def analyze_log(log_rdd):
    # Filter out blank lines
    non_empty_lines_rdd = log_rdd.filter(lambda line: line.strip() != '')
    
    ip_rdd = non_empty_lines_rdd.map(lambda line: line.split(' ')[0])
    ip_count_rdd = ip_rdd.map(lambda ip: (ip, 1))
    ip_counts = ip_count_rdd.reduceByKey(lambda a, b: a + b)
    
    result = ip_counts.collectAsMap()
    return result`

2024-09-05 23:31 UTC, pcamarillor requested changes
In order to merge your PR, please discard changes in the notebook example

2024-09-05 23:31 UTC, pcamarillor commented on src/lab02/solution_lab02_gabriel_olvera.py
> +    non_empty_lines_rdd = log_rdd.filter(lambda line: line.strip() != '')
Cool !

2025-01-26 01:32 UTC, closed without merging